name: Github Action 테스트 1번

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 출력
        run: echo "Hello World"

      - name: 여러개 명령어 추가하기
        run: |
          echo "Good"
          echo "Morning"

      - name: 깃허브의 내장변수 사용
        run: |
          echo "1. Commit SHA : $GITHUB_SHA"
          echo "2. Repository : $GITHUB_REPOSITORY"
          echo "3. 워크플로우 실행한 사람 : $GITHUB_ACTOR"
          echo "4. 현재 실행중인 브랜치 : $GITHUB_REF_NAME"
          echo "5. 현재 실행 번호 : $GITHUB_RUN_NUMBER"
          echo "6. 현재 실행 이벤트 : $GITHUB_EVENT_NAME"
          echo "7. 현재 실행중인 OS : $RUNNER_OS"
          echo "8. 기본 작업 경로 : $GITHUB_WORKSPACE"